/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.core;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author omem-
 */
public class Cash extends javax.swing.JPanel {

    double[] dolar = {1,        16.88,  0.90,   0.78,   139.90};   //Dolar, Pesos, Euro, Libras, Yenes
    double[] pesos = {0.059,    1,      0.053,  0.046,  8.29};   
    double[] euro =  {1.11,     18.81,  1,      0.87,   155.86};
    double[] libras ={1.29,     21.73,  1.16,   1,      180.15};
    double[] yenes = {0.0071,   0.12,   0.0064, 0.0055, 1};
    
    double[][] monedas = {{1,        16.88,  0.90,   0.78,   139.90},
                          {0.059,    1,      0.053,  0.046,  8.29},
                          {1.11,     18.81,  1,      0.87,   155.86},
                          {1.29,     21.73,  1.16,   1,      180.15},
                          {0.0071,   0.12,   0.0064, 0.0055, 1}};
    /**
     * Creates new form Cash
     */
    public Cash() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Input1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        JError = new javax.swing.JLabel();
        jBChange = new javax.swing.JButton();
        Input2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(630, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Convertidor de monedas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Input1.setToolTipText("");
        add(Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Pesos", "Euro", "Libras", "Yenes" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 120, 40));

        JError.setForeground(new java.awt.Color(255, 0, 51));
        add(JError, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jBChange.setText("Convertir");
        jBChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangeActionPerformed(evt);
            }
        });
        add(jBChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, 40));

        Input2.setEditable(false);
        add(Input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 210, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Pesos", "Euro", "Libras", "Yenes" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 120, 40));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jBChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangeActionPerformed
        // TODO add your handling code here:
        int index1 = jComboBox1.getSelectedIndex();
        int index2 = jComboBox2.getSelectedIndex();
        //System.out.println(index1+ " "+ index2);
        //System.out.println(monedas[index1][index2]);
        Money money = new Money(monedas, index1);
        
        
        //DecimalFormat df = new DecimalFormat("#.000");
        
        JError.setText("");
        try {
        //System.out.println("texto: "+Input1.getText());
        double qt = Double.parseDouble(Input1.getText());
        double result =  money.setConvert(qt, index2 );
        Input2.setText(String.format("%.3f", result) ); //String.valueOf(result)
            
        } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(null, "Solo números", "Error", JOptionPane.ERROR_MESSAGE);
          JError.setText("Error solo se aceptan números");
        }
        

        
        
    }//GEN-LAST:event_jBChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input1;
    private javax.swing.JTextField Input2;
    private javax.swing.JLabel JError;
    private javax.swing.JButton jBChange;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
