/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.core;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author omem-
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Cash cash = new Cash();
        ShowPanel(cash);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelButton1 = new javax.swing.JPanel();
        jLabelMoney = new javax.swing.JLabel();
        jPanelButton2 = new javax.swing.JPanel();
        jLabelTemp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jPanelButton1.setBackground(new java.awt.Color(51, 153, 255));
        jPanelButton1.setForeground(new java.awt.Color(0, 153, 255));

        jLabelMoney.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMoney.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMoney.setText("Monedas");
        jLabelMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMoneyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMoneyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMoneyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButton1Layout = new javax.swing.GroupLayout(jPanelButton1);
        jPanelButton1.setLayout(jPanelButton1Layout);
        jPanelButton1Layout.setHorizontalGroup(
            jPanelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelButton1Layout.setVerticalGroup(
            jPanelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jPanelButton2.setBackground(new java.awt.Color(51, 153, 255));
        jPanelButton2.setForeground(new java.awt.Color(0, 153, 255));

        jLabelTemp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTemp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTemp.setText("Temperatura");
        jLabelTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTempMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTempMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTempMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButton2Layout = new javax.swing.GroupLayout(jPanelButton2);
        jPanelButton2.setLayout(jPanelButton2Layout);
        jPanelButton2Layout.setHorizontalGroup(
            jPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelButton2Layout.setVerticalGroup(
            jPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jPanelBg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Challenge-Conversor");

        jLabel2.setText("By Guillermo Navarro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanelBg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 630, 120));

        content.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanelBg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 630, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMoneyMouseClicked
        // TODO add your handling code here:
        Cash cash = new Cash();
        ShowPanel(cash);
    }//GEN-LAST:event_jLabelMoneyMouseClicked

    private void jLabelTempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTempMouseClicked
        // TODO add your handling code here:
        Temp temp = new Temp();
        ShowPanel(temp);
    }//GEN-LAST:event_jLabelTempMouseClicked

    private void jLabelMoneyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMoneyMouseEntered
        // TODO add your handling code here:
        jLabelMoney.setFont(new java.awt.Font("Segoe UI", 1, 20));
    }//GEN-LAST:event_jLabelMoneyMouseEntered

    private void jLabelMoneyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMoneyMouseExited
        // TODO add your handling code here:
        jLabelMoney.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_jLabelMoneyMouseExited

    private void jLabelTempMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTempMouseEntered
        // TODO add your handling code here:
         jLabelTemp.setFont(new java.awt.Font("Segoe UI", 1, 20));
    }//GEN-LAST:event_jLabelTempMouseEntered

    private void jLabelTempMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTempMouseExited
        // TODO add your handling code here:
         jLabelTemp.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_jLabelTempMouseExited

        private void ShowPanel(JPanel p){
        
        p.setSize(790, 440); 
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelTemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBg;
    private javax.swing.JPanel jPanelButton1;
    private javax.swing.JPanel jPanelButton2;
    // End of variables declaration//GEN-END:variables
}
