/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.core;

import javax.swing.JOptionPane;

/**
 *
 * @author omem-
 */
public class Temp extends javax.swing.JPanel {

    /**
     * Creates new form Temp
     */
    public Temp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Input1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBResult = new javax.swing.JButton();
        Input2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        JError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(630, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelvin", "Fahrenheit" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 120, 50));

        jBResult.setText("Convertir");
        jBResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResultActionPerformed(evt);
            }
        });
        add(jBResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 100, 50));
        add(Input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 180, 50));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelvin", "Fahrenheit" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 120, 52));

        JError.setForeground(new java.awt.Color(255, 0, 0));
        add(JError, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Convertidor de temperatura");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResultActionPerformed
        // TODO add your handling code here:
        JError.setText("");
        int index1 = jComboBox1.getSelectedIndex();
        int index2 = jComboBox2.getSelectedIndex();

        
          try {
            double qt = Double.parseDouble(Input1.getText());
            Temperatura temp = new Temperatura(index1, qt);
            Operations op = new Operations(temp);
            double rs  = op.changesTemps(index2);
            Input2.setText(String.format("%.3f", rs) );
      
        } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(null, "Solo números", "Error", JOptionPane.ERROR_MESSAGE);
          JError.setText("Error solo se aceptan números");
        }
        
        
    }//GEN-LAST:event_jBResultActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input1;
    private javax.swing.JTextField Input2;
    private javax.swing.JLabel JError;
    private javax.swing.JButton jBResult;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
